name: trac_nghiem
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.10
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  path: ^1.8.3
#  flutter_launcher_icons: ^0.14.4
  url_launcher: ^6.1.12
  permission_handler: ^12.0.0+1
  image_picker: ^1.0.7
  intl: ^0.18.1
  qr_flutter: ^4.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4


flutter_icons:
  android: true
  ios: false
  image_path: "assets/images/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
